AWSTemplateFormatVersion: 2010-09-09

Resources:
  BucketCMK:
    Type: 'AWS::KMS::Key'
    Properties:
      EnableKeyRotation: true
      MultiRegion: false
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable the IAM Permissions for Root
            Effect: Allow
            Principal:
              AWS:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:iam::'
                    - Ref: 'AWS::AccountId'
                    - ':root'
            Action: 'kms:*'
            Resource: '*'

  KMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/keyForS3
      TargetKeyId:
        Ref: BucketCMK

  DeploymentBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub onp-${AWS::AccountId}-deployment-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt BucketCMK.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpiryRule
            Status: Enabled
            ExpirationInDays: 14
    DependsOn: BucketCMK

  DeploymentBucketSSMParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /onp/bootstrap/deploymentbucket
      Type: String
      Value: !Ref DeploymentBucket
      Description: Name of the deployment bucket